using System.Text.Json.Serialization;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     A tool call that applies file diffs by creating, deleting, or updating files.
///     <see href="https://platform.openai.com/docs/api-reference/responses">OpenAI API documentation</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/applypatchtoolcall.yml">
///         Source Definition
///     </see>
/// </summary>
public class ApplyPatchToolCall : IInputItem, IOutputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ApplyPatchToolCall" /> class.
    /// </summary>
    public ApplyPatchToolCall()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="ApplyPatchToolCall" /> class with required parameters.
    /// </summary>
    /// <param name="id">The unique ID of the apply patch tool call.</param>
    /// <param name="callId">The unique ID of the apply patch tool call generated by the model.</param>
    /// <param name="status">The status of the call.</param>
    public ApplyPatchToolCall(string id, string callId, string status)
    {
        Id = id;
        CallId = callId;
        Status = status;
    }

    /// <summary>
    ///     The type of the item. Always <c>apply_patch_call</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "apply_patch_call";

    /// <summary>
    ///     The unique ID of the apply patch tool call. Populated when this item is returned via API.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = null!;

    /// <summary>
    ///     The unique ID of the apply patch tool call generated by the model.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string CallId { get; set; } = null!;

    /// <summary>
    ///     The status of the call.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = null!;

    /// <summary>
    ///     The operation to apply (create_file, delete_file, or update_file).
    /// </summary>
    [JsonPropertyName("operation")]
    public ApplyPatchOperation? Operation { get; set; }

    /// <summary>
    ///     The ID of the entity that created this tool call.
    /// </summary>
    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; set; }
}

/// <summary>
///     An operation applied via apply_patch.
/// </summary>
public class ApplyPatchOperation
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ApplyPatchOperation" /> class.
    /// </summary>
    public ApplyPatchOperation()
    {
    }

    /// <summary>
    ///     The type of the operation. One of <c>create_file</c>, <c>delete_file</c>, or <c>update_file</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>
    ///     The path of the file.
    /// </summary>
    [JsonPropertyName("path")]
    public string? Path { get; set; }

    /// <summary>
    ///     The content of the file (for create or update operations).
    /// </summary>
    [JsonPropertyName("content")]
    public string? Content { get; set; }

    /// <summary>
    ///     The patch to apply (for update operations).
    /// </summary>
    [JsonPropertyName("patch")]
    public string? Patch { get; set; }
}




