using System.Text.Json.Serialization;
using Betalgo.Ranul.OpenAI.Contracts.Enums.Responses;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     A tool call to run code.
///     <see href="https://platform.openai.com/docs/guides/code-interpreter">Code Interpreter Guide</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/codeinterpretertoolcall.yml">
///         Source Definition
///     </see>
/// </summary>
public class CodeInterpreterToolCall : IOutputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="CodeInterpreterToolCall" /> class.
    /// </summary>
    public CodeInterpreterToolCall()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="CodeInterpreterToolCall" /> class with required parameters.
    /// </summary>
    /// <param name="id">The unique ID of the code interpreter tool call.</param>
    /// <param name="status">The status of the code interpreter tool call.</param>
    /// <param name="containerId">The ID of the container used to run the code.</param>
    /// <param name="code">The code to run.</param>
    /// <param name="outputs">The outputs generated by the code interpreter.</param>
    public CodeInterpreterToolCall(string id, CodeInterpreterCallStatus status, string containerId, string? code, List<ICodeInterpreterOutput>? outputs)
    {
        Id = id;
        Status = status;
        ContainerId = containerId;
        Code = code;
        Outputs = outputs;
    }

    /// <summary>
    ///     The type of the code interpreter tool call. Always <c>code_interpreter_call</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "code_interpreter_call";

    /// <summary>
    ///     The unique ID of the code interpreter tool call.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = null!;

    /// <summary>
    ///     The status of the code interpreter tool call.
    ///     Valid values are <c>in_progress</c>, <c>completed</c>, <c>incomplete</c>, <c>interpreting</c>, and <c>failed</c>.
    /// </summary>
    [JsonPropertyName("status")]
    public CodeInterpreterCallStatus Status { get; set; }

    /// <summary>
    ///     The ID of the container used to run the code.
    /// </summary>
    [JsonPropertyName("container_id")]
    public string ContainerId { get; set; } = null!;

    /// <summary>
    ///     The code to run, or null if not available.
    /// </summary>
    [JsonPropertyName("code")]
    public string? Code { get; set; }

    /// <summary>
    ///     The outputs generated by the code interpreter, such as logs or images.
    ///     Can be null if no outputs are available.
    /// </summary>
    [JsonPropertyName("outputs")]
    public List<ICodeInterpreterOutput>? Outputs { get; set; }
}

