using System.Text.Json.Serialization;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     A call to a custom tool created by the model.
///     <see href="https://platform.openai.com/docs/guides/function-calling#custom-tools">Custom Tools Guide</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/customtoolcall.yml">
///         Source Definition
///     </see>
/// </summary>
public class CustomToolCall : IInputItem, IOutputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="CustomToolCall" /> class.
    /// </summary>
    public CustomToolCall()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="CustomToolCall" /> class with required parameters.
    /// </summary>
    /// <param name="callId">An identifier used to map this custom tool call to a tool call output.</param>
    /// <param name="name">The name of the custom tool being called.</param>
    /// <param name="input">The input for the custom tool call generated by the model.</param>
    public CustomToolCall(string callId, string name, string input)
    {
        CallId = callId;
        Name = name;
        Input = input;
    }

    /// <summary>
    ///     The type of the custom tool call. Always <c>custom_tool_call</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "custom_tool_call";

    /// <summary>
    ///     The unique ID of the custom tool call in the OpenAI platform.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    ///     An identifier used to map this custom tool call to a tool call output.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string CallId { get; set; } = null!;

    /// <summary>
    ///     The name of the custom tool being called.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = null!;

    /// <summary>
    ///     The input for the custom tool call generated by the model.
    /// </summary>
    [JsonPropertyName("input")]
    public string Input { get; set; } = null!;
}




