using System.Text.Json.Serialization;
using Betalgo.Ranul.OpenAI.Contracts.Enums.Responses;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     The output of a function tool call.
///     <see href="https://platform.openai.com/docs/guides/function-calling">Function Calling Guide</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/functioncalloutputitemparam.yml">
///         Source Definition
///     </see>
/// </summary>
public class FunctionCallOutputItemParam : IInputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionCallOutputItemParam" /> class.
    /// </summary>
    public FunctionCallOutputItemParam()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionCallOutputItemParam" /> class with required parameters.
    /// </summary>
    /// <param name="callId">The unique ID of the function tool call generated by the model.</param>
    /// <param name="output">The output of the function tool call (JSON string or array of content).</param>
    public FunctionCallOutputItemParam(string callId, object output)
    {
        CallId = callId;
        Output = output;
    }

    /// <summary>
    ///     The type of the function tool call output. Always <c>function_call_output</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "function_call_output";

    /// <summary>
    ///     The unique ID of the function tool call output. Populated when this item is returned via API.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    ///     The unique ID of the function tool call generated by the model.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string CallId { get; set; } = null!;

    /// <summary>
    ///     The output of the function tool call. Can be a JSON string or an array of content items.
    /// </summary>
    [JsonPropertyName("output")]
    public object Output { get; set; } = null!;

    /// <summary>
    ///     The status of the item.
    /// </summary>
    [JsonPropertyName("status")]
    public ItemStatus? Status { get; set; }
}

