using System.Text.Json.Serialization;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     A tool call that executes one or more shell commands in a managed environment.
///     <see href="https://platform.openai.com/docs/api-reference/responses">OpenAI API documentation</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/functionshellcall.yml">
///         Source Definition
///     </see>
/// </summary>
public class FunctionShellCall : IInputItem, IOutputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionShellCall" /> class.
    /// </summary>
    public FunctionShellCall()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionShellCall" /> class with required parameters.
    /// </summary>
    /// <param name="id">The unique ID of the function shell tool call.</param>
    /// <param name="callId">The unique ID of the function shell tool call generated by the model.</param>
    /// <param name="status">The status of the call.</param>
    public FunctionShellCall(string id, string callId, string status)
    {
        Id = id;
        CallId = callId;
        Status = status;
    }

    /// <summary>
    ///     The type of the item. Always <c>shell_call</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "shell_call";

    /// <summary>
    ///     The unique ID of the function shell tool call. Populated when this item is returned via API.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = null!;

    /// <summary>
    ///     The unique ID of the function shell tool call generated by the model.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string CallId { get; set; } = null!;

    /// <summary>
    ///     The action to execute.
    /// </summary>
    [JsonPropertyName("action")]
    public FunctionShellAction? Action { get; set; }

    /// <summary>
    ///     The status of the call.
    ///     One of <c>in_progress</c>, <c>completed</c>, or <c>incomplete</c>.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = null!;

    /// <summary>
    ///     The ID of the entity that created this tool call.
    /// </summary>
    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; set; }
}

/// <summary>
///     The action to execute in a function shell call.
/// </summary>
public class FunctionShellAction
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionShellAction" /> class.
    /// </summary>
    public FunctionShellAction()
    {
    }

    /// <summary>
    ///     The type of the action.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>
    ///     The command to execute.
    /// </summary>
    [JsonPropertyName("command")]
    public List<string>? Command { get; set; }

    /// <summary>
    ///     Environment variables for the command.
    /// </summary>
    [JsonPropertyName("env")]
    public Dictionary<string, string>? Env { get; set; }

    /// <summary>
    ///     The working directory for the command.
    /// </summary>
    [JsonPropertyName("working_directory")]
    public string? WorkingDirectory { get; set; }

    /// <summary>
    ///     Timeout in milliseconds.
    /// </summary>
    [JsonPropertyName("timeout_ms")]
    public int? TimeoutMs { get; set; }
}




