using System.Text.Json.Serialization;
using Betalgo.Ranul.OpenAI.Contracts.Enums.Responses;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     A tool call to run a function. See the
///     <see href="https://platform.openai.com/docs/guides/function-calling">function calling guide</see> for more
///     information.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/functiontoolcall.yml">
///         Source Definition
///     </see>
/// </summary>
public class FunctionToolCallItem : IInputItem, IOutputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionToolCallItem" /> class.
    /// </summary>
    public FunctionToolCallItem()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="FunctionToolCallItem" /> class with required parameters.
    /// </summary>
    /// <param name="callId">The unique ID of the function tool call generated by the model.</param>
    /// <param name="name">The name of the function to run.</param>
    /// <param name="arguments">A JSON string of the arguments to pass to the function.</param>
    public FunctionToolCallItem(string callId, string name, string arguments)
    {
        CallId = callId;
        Name = name;
        Arguments = arguments;
    }

    /// <summary>
    ///     The type of the function tool call. Always <c>function_call</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "function_call";

    /// <summary>
    ///     The unique ID of the function tool call generated by the model.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string CallId { get; set; } = null!;

    /// <summary>
    ///     The name of the function to run.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = null!;

    /// <summary>
    ///     A JSON string of the arguments to pass to the function.
    /// </summary>
    [JsonPropertyName("arguments")]
    public string Arguments { get; set; } = null!;

    /// <summary>
    ///     The unique ID of the function tool call.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    ///     The status of the item. One of <c>in_progress</c>, <c>completed</c>, or <c>incomplete</c>.
    ///     Populated when items are returned via API.
    /// </summary>
    [JsonPropertyName("status")]
    public ItemStatus? Status { get; set; }
}
