using System.Text.Json.Serialization;

namespace Betalgo.Ranul.OpenAI.Contracts.Types.Items;

/// <summary>
///     A tool call to run a command on the local shell.
///     <see href="https://platform.openai.com/docs/api-reference/responses">OpenAI API documentation</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/localshelltoolcall.yml">
///         Source Definition
///     </see>
/// </summary>
public class LocalShellToolCall : IInputItem, IOutputItem
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="LocalShellToolCall" /> class.
    /// </summary>
    public LocalShellToolCall()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="LocalShellToolCall" /> class with required parameters.
    /// </summary>
    /// <param name="id">The unique ID of the local shell call.</param>
    /// <param name="callId">The unique ID of the local shell tool call generated by the model.</param>
    /// <param name="status">The status of the local shell call.</param>
    public LocalShellToolCall(string id, string callId, string status)
    {
        Id = id;
        CallId = callId;
        Status = status;
    }

    /// <summary>
    ///     The type of the local shell call. Always <c>local_shell_call</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "local_shell_call";

    /// <summary>
    ///     The unique ID of the local shell call.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = null!;

    /// <summary>
    ///     The unique ID of the local shell tool call generated by the model.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string CallId { get; set; } = null!;

    /// <summary>
    ///     The action to execute.
    /// </summary>
    [JsonPropertyName("action")]
    public LocalShellExecAction? Action { get; set; }

    /// <summary>
    ///     The status of the local shell call.
    ///     One of <c>in_progress</c>, <c>completed</c>, or <c>incomplete</c>.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = null!;
}

/// <summary>
///     The action to execute in a local shell call.
/// </summary>
public class LocalShellExecAction
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="LocalShellExecAction" /> class.
    /// </summary>
    public LocalShellExecAction()
    {
    }

    /// <summary>
    ///     The type of the action. Always <c>exec</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "exec";

    /// <summary>
    ///     The command to execute.
    /// </summary>
    [JsonPropertyName("command")]
    public List<string>? Command { get; set; }

    /// <summary>
    ///     Environment variables for the command.
    /// </summary>
    [JsonPropertyName("env")]
    public Dictionary<string, string>? Env { get; set; }

    /// <summary>
    ///     The working directory for the command.
    /// </summary>
    [JsonPropertyName("working_directory")]
    public string? WorkingDirectory { get; set; }

    /// <summary>
    ///     The user to run the command as.
    /// </summary>
    [JsonPropertyName("user")]
    public string? User { get; set; }

    /// <summary>
    ///     Timeout in milliseconds.
    /// </summary>
    [JsonPropertyName("timeout_ms")]
    public int? TimeoutMs { get; set; }
}




