using System.Text.Json.Serialization;
using Betalgo.Ranul.OpenAI.Contracts.Enums.Responses;
using Betalgo.Ranul.OpenAI.Contracts.Interfaces;
using Betalgo.Ranul.OpenAI.Contracts.Responses.Base;
using Betalgo.Ranul.OpenAI.Contracts.Types;
using Betalgo.Ranul.OpenAI.Contracts.Types.ToolChoice;
using Betalgo.Ranul.OpenAI.Contracts.Types.Tools;

namespace Betalgo.Ranul.OpenAI.Contracts.Responses.Responses;

/// <summary>
///     The response object from the Responses API.
///     <see href="https://platform.openai.com/docs/api-reference/responses/object">OpenAI API documentation</see>.
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/response.yml">
///         Source Definition
///     </see>
/// </summary>
public class Response : ResponseBase, IDefaultResult<Response>
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="Response" /> class.
    /// </summary>
    public Response()
    {
    }

    /// <summary>
    ///     Gets this instance as the result for <see cref="IDefaultResult{T}" />.
    /// </summary>
    [JsonIgnore]
    public Response? Result => Successful ? this : null;

    /// <summary>
    ///     Unique identifier for this Response.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = null!;

    /// <summary>
    ///     The status of the response generation. One of <c>completed</c>, <c>failed</c>,
    ///     <c>in_progress</c>, <c>cancelled</c>, <c>queued</c>, or <c>incomplete</c>.
    /// </summary>
    [JsonPropertyName("status")]
    public ResponsesStatus? Status { get; set; }

    /// <summary>
    ///     Unix timestamp (in seconds) of when this Response was created.
    /// </summary>
    [JsonPropertyName("created_at")]
    public long? CreatedAt { get; set; }

    /// <summary>
    ///     The model used to generate the response.
    /// </summary>
    [JsonPropertyName("model")]
    public string? Model { get; set; }

    /// <summary>
    ///     An array of content items generated by the model.
    /// </summary>
    [JsonPropertyName("output")]
    public List<IOutputItem>? Output { get; set; }

    /// <summary>
    ///     SDK-only convenience property that contains the aggregated text output from all <c>output_text</c> items.
    /// </summary>
    [JsonPropertyName("output_text")]
    public string? OutputText { get; set; }

    /// <summary>
    ///     A system (or developer) message inserted into the model's context.
    /// </summary>
    [JsonPropertyName("instructions")]
    public string? Instructions { get; set; }

    /// <summary>
    ///     Details about why the response is incomplete, if applicable.
    /// </summary>
    [JsonPropertyName("incomplete_details")]
    public IncompleteDetails? IncompleteDetails { get; set; }

    /// <summary>
    ///     Set of 16 key-value pairs that can be attached to an object.
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; set; }

    /// <summary>
    ///     Whether to allow the model to run tool calls in parallel.
    /// </summary>
    [JsonPropertyName("parallel_tool_calls")]
    public bool? ParallelToolCalls { get; set; }

    /// <summary>
    ///     The unique ID of the previous response to the model.
    /// </summary>
    [JsonPropertyName("previous_response_id")]
    public string? PreviousResponseId { get; set; }

    /// <summary>
    ///     Configuration for reasoning models.
    /// </summary>
    [JsonPropertyName("reasoning")]
    public ResponsesReasoningConfig? Reasoning { get; set; }

    /// <summary>
    ///     The sampling temperature used.
    /// </summary>
    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; }

    /// <summary>
    ///     Configuration for the response's text format.
    /// </summary>
    [JsonPropertyName("text")]
    public ResponsesTextConfig? Text { get; set; }

    /// <summary>
    ///     How the model selected which tool to call.
    /// </summary>
    [JsonPropertyName("tool_choice")]
    public ToolChoice? ToolChoice { get; set; }

    /// <summary>
    ///     The array of tools the model could call.
    /// </summary>
    [JsonPropertyName("tools")]
    public List<ITool>? Tools { get; set; }

    /// <summary>
    ///     The nucleus sampling value used.
    /// </summary>
    [JsonPropertyName("top_p")]
    public double? TopP { get; set; }

    /// <summary>
    ///     The truncation strategy used.
    /// </summary>
    [JsonPropertyName("truncation")]
    public TruncationStrategy? Truncation { get; set; }

    /// <summary>
    ///     Token usage information for the response.
    /// </summary>
    [JsonPropertyName("usage")]
    public ResponsesUsage? Usage { get; set; }

    /// <summary>
    ///     The user identifier.
    ///     This field is being replaced by <see cref="SafetyIdentifier" /> and <see cref="PromptCacheKey" />.
    ///     Use <see cref="PromptCacheKey" /> instead to maintain caching optimizations.
    /// </summary>
    [Obsolete("This field is being replaced by SafetyIdentifier and PromptCacheKey. Use PromptCacheKey instead to maintain caching optimizations.")]
    [JsonPropertyName("user")]
    public string? User { get; set; }

    /// <summary>
    ///     A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.
    ///     <see href="https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers">Learn more</see>.
    /// </summary>
    [JsonPropertyName("safety_identifier")]
    public string? SafetyIdentifier { get; set; }

    /// <summary>
    ///     Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the User field.
    ///     <see href="https://platform.openai.com/docs/guides/prompt-caching">Learn more</see>.
    /// </summary>
    [JsonPropertyName("prompt_cache_key")]
    public string? PromptCacheKey { get; set; }

    /// <summary>
    ///     The retention policy for the prompt cache.
    ///     <see href="https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention">Learn more</see>.
    /// </summary>
    [JsonPropertyName("prompt_cache_retention")]
    public PromptCacheRetention? PromptCacheRetention { get; set; }

    /// <summary>
    ///     The service tier used for serving the request.
    /// </summary>
    [JsonPropertyName("service_tier")]
    public ServiceTier? ServiceTier { get; set; }

    /// <summary>
    ///     An integer between 0 and 20 specifying the number of most likely tokens to return at each token position,
    ///     each with an associated log probability.
    /// </summary>
    [JsonPropertyName("top_logprobs")]
    public int? TopLogprobs { get; set; }

    /// <summary>
    ///     Whether to run the model response in the background.
    ///     <see href="https://platform.openai.com/docs/guides/background">Learn more</see>.
    /// </summary>
    [JsonPropertyName("background")]
    public bool? Background { get; set; }

    /// <summary>
    ///     The maximum number of total calls to built-in tools that can be processed in a response.
    /// </summary>
    [JsonPropertyName("max_tool_calls")]
    public int? MaxToolCalls { get; set; }

    /// <summary>
    ///     The maximum number of output tokens.
    /// </summary>
    [JsonPropertyName("max_output_tokens")]
    public int? MaxOutputTokens { get; set; }

    /// <summary>
    ///     The conversation that this response belongs to. Input items and output items from this response
    ///     are automatically added to this conversation.
    /// </summary>
    [JsonPropertyName("conversation")]
    public ConversationResponse? Conversation { get; set; }
}
